name: Python Code Checks

on:
  - push
  - pull_request
  
jobs:
  format-and-typecheck:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Tesseract-OCR
      run: sudo apt-get install tesseract-ocr

    - name: Run isort
      run: |
         isort .

    - name: Run black
      run: |
        black . --check --diff
